#!/usr/bin/env bash
# Script that configures a load balancer for Ubuntu 20.04

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\
frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 512-web-01 52.91.126.74 check
	server 512-web-02 100.26.240.229 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart